# -*- coding: utf-8 -*-
"""TASK 1 EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LJV_W_lS6daSJZ1cD1ek-mbPxibsXMw_
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import io
df=pd.read_csv(io.BytesIO(uploaded['student-dataset.csv']))
df.head()

df.tail()

df.describe()

df.columns

df.nunique()

df.isnull().sum()

sns.pairplot(df)

sns.distplot(df['age'])

